version: "3.8"

volumes:
  db_volume:
    driver: local

networks:
  php_advanced:
    driver: bridge

servicer:
  app:
    build:
      context: docker/php
    restart: always
    valumes:
      - .:/var/www/html
    ports:
      - "8081:80"
    networks:
      - php_advanced
  db:
    image: "mysql:8"
    restar: always
    ports: -"33060:3306"
    volumes:
      - "db_valume:/var/lib/mysql"
    networks:
      - php_advanced
