version: "3.8"

volumes:
  db_volume:
    driver: local

networks:
  php_advanced:
    driver: bridge

services:
  app:
    build:
      context: .docker/php
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - "8081:80"
    networks:
      - php_advanced
  db:
    image: "mysql:8"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secrit
    ports:
      - "33060:3306"
    volumes:
      - "db_volume:/var/lib/mysql"
    networks:
      - php_advanced
